# Generated by Django 5.0.3 on 2024-05-25 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('payment_url', models.TextField(blank=True, null=True)),
                ('payment_id', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='ServerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название локации')),
                ('solar', models.PositiveSmallIntegerField(verbose_name='Цена в rub за месяц пользования')),
            ],
            options={
                'verbose_name': 'Локация сервера',
                'verbose_name_plural': 'Локации серверов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('count_configs', models.PositiveSmallIntegerField(verbose_name='Количество конфигов')),
                ('is_own_server', models.BooleanField(verbose_name='Создавать новый сервер')),
                ('solar', models.PositiveIntegerField(verbose_name='Стоимость заказа')),
                ('status', models.CharField(choices=[('created', 'Сформирован'), ('payed', 'Оплачен'), ('working', 'В обработке'), ('done', 'Выполнен')], default='created', max_length=40)),
                ('services', models.CharField(default='["vpn"]', max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.payment')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.serverlocation')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ConfigKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField()),
                ('method', models.CharField(max_length=50)),
                ('accessUrl', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'configs_key',
            },
        ),
        migrations.CreateModel(
            name='OrderOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiUrl', models.TextField(verbose_name='Ссылка на api')),
                ('certSha256', models.TextField(verbose_name='Токен доступа к manager')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'order_outlines',
            },
        ),
    ]
