# Generated by Django 5.0.3 on 2024-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlocation',
            name='basePrice',
            field=models.PositiveSmallIntegerField(default=300, verbose_name='Цена в rub за месяц пользования'),
            preserve_default=False,
        ),
    ]
