# Generated by Django 5.0.3 on 2024-03-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_serverlocation_baseprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverlocation',
            old_name='basePrice',
            new_name='solar',
        ),
    ]
