# Generated by Django 5.0.3 on 2024-04-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderstatuses_payment_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.DeleteModel(
            name='OrderStatuses',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Сформирован'), ('payed', 'Оплачен'), ('working', 'В обработке'), ('done', 'Выполнен')], default=('created', 'Сформирован'), max_length=40),
        ),
    ]
