# Generated by Django 5.0.3 on 2024-04-16 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField()),
                ('method', models.CharField(max_length=50)),
                ('accessUrl', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'configs_key',
            },
        ),
        migrations.CreateModel(
            name='OrderOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiUrl', models.TextField(verbose_name='Ссылка на api')),
                ('certSha256', models.TextField(verbose_name='Токен доступа к manager')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'order_outlines',
            },
        ),
    ]
