# Generated by Django 5.0.3 on 2024-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_configkey_orderoutline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.CharField(default='["vpn"]', max_length=100),
        ),
    ]
